name: Production (store)

on:
  workflow_dispatch: {}

jobs:
  build_android_apk:
    name: Android APK (download page)
    type: build
    environment: production
    params:
      platform: android
      profile: production-apk
      message: EAS Workflow production Android APK
  build_android:
    name: Android AAB
    type: build
    environment: production
    params:
      platform: android
      profile: production
      message: EAS Workflow production Android AAB
  build_ios:
    name: iOS App Store
    type: build
    environment: production
    params:
      platform: ios
      profile: production
      message: EAS Workflow production iOS
